### PR TITLE
issue301 Closes #301 Adds an htmlEntity helper for entities that should ...

### LINKED ISSUE #301: unescapeHTML does not work with &nbsp;
When I try to unescape ```&nbsp;``` it does not work. For example if I run this code:

```
console.log _s.unescapeHTML("&nbsp;")
```
it outputs ```&nbsp;```

Can this be done using underscore.string?

### PR DESCRIPTION
**Pull request by srmelody**
...be unescaped but do not need to be scaped.  We can use the escapeChars helper to handle the smaller set of html escape chars

Please note that I did not commit the dist/ files.  My assumption is they get built at release time.  I also added a set of the html entities, but it's not exhaustive.  I could remove the extras and just add nbsp to the escape codes array.

### CODE REVIEW

File: tests/unescapeHTML.js [hunk 1]
```diff
@@ -17,8 +17,8 @@ test('#unescapeHTML', function(){
   equal(unescapeHTML('&amp;#38;'), '&#38;');
   equal(unescapeHTML('&#38;amp;'), '&amp;');
   equal(unescapeHTML(''), '');
+  equal(unescapeHTML('&nbsp;'), ' ');
```
Comment (stoeffel) [inline tests/unescapeHTML.js]: Could you add tests for all the htmlEntities?

**Comment by stoeffel** [comment]
How about adding support for this additional htmlEntities to `escapeHtml` (except `&nbsp`) too?

**Comment by stoeffel** [comment]
Maybe a list of supported htmlEntities in the readme would be nice for users.

**Comment by srmelody** [comment]
@stoeffel I addressed your great feedback, thanks.  Let me know if you see any issues with the updated commit.

**Comment by stoeffel** [comment]
If 'helpers/escapeChars' is only used in `escapeHtml`, the keys and values could be swapped instead of swapping it in the for loop ( I didn't check if it isn't used anywhere else, I'm on my phone :smile:). Thanks for your changes.

**Comment by srmelody** [comment]
Yes, I was able to remove the map reversing and explicitly build the escapeChars map once.  Good suggestion :smile:

**Comment by srmelody** [comment]
Anything else @stoeffel ?

**Comment by stoeffel** [comment]
No, I think it looks good. I will check again as soon as I have time and then merge it. Thanks

File: helper/htmlEntities.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+  pound: '£',
+  yen: '¥',
+  euro: '€',
+  copy: '©',
+  reg: '®',
+  lt: '<',
+  gt: '>',
+  quot: '"',
+  amp: '&',
+  '#39': "'",
```
Comment (stoeffel) [inline helper/htmlEntities.js]: There is no need for this. Checkout line 12 in `unescapeHtml`.

**Comment by srmelody** [comment]
@stoeffel I removed the line you called out.  Thanks. :)

**Comment by stoeffel** [comment]
Thanks;
